org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neoforge_version=21.1.230
neoforge_version_range=[21.1,)
loader_version_range=[4,)
mapping_channel=official
mapping_version=1.21.1

mod_id=cbc_terminal_ballistics
mod_name=CBC Terminal Ballistics
mod_license=CC BY-NC-SA 4.0
mod_version=0.3.4-neoforge
mod_group_id=com.cbc_terminal_ballistics
mod_authors=Erika, MegiTicky
create_version=6.0.10-281
ponder_version=1.0.56
registrate_version=MC1.21-1.3.0+62
cbc_modrinth_project=GWp4jCJj
cbc_modrinth_version=bOiDu0LS
mod_description=Create Big Cannons add-on adding material-aware terminal ballistics, armor integrity, spall, impact marks, and copycat armor blocks.
