modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[mixins]]
config="cbc_terminal_ballistics.mixins.json"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="[6.0.8,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="copycats"
    mandatory=true
    versionRange="[3.0.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="createbigcannons"
    mandatory=true
    versionRange="[5.10.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cbcmoreshells"
    mandatory=false
    versionRange="[0.2.2,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="cbcmodernwarfare"
    mandatory=false
    versionRange="[0.0.7,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="rha"
    mandatory=false
    versionRange="[1.1.5,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="s_a_b"
    mandatory=false
    versionRange="[1.4.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="valkyrienskies"
    mandatory=false
    versionRange="[2.4.7,)"
    ordering="AFTER"
    side="BOTH"
