modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neoforge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="create"
    mandatory=true
    versionRange="[6.0.7,6.1.0)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="copycats"
    mandatory=true
    versionRange="[3.0.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="createbigcannons"
    mandatory=true
    versionRange="[5.10,5.12)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="sable"
    type="optional"
    versionRange="[1.2.2,3.0.0)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="aeronautics"
    type="optional"
    versionRange="[1.2.1,)"
    ordering="AFTER"
    side="BOTH"

[[mixins]]
    config="cbc_terminal_ballistics.mixins.json"
